### ISSUE TITLE
General usage clarification

### ISSUE THREAD

**Issue by danlamanna** [nlamirault/emacs-travis#5]
Hi, thanks for this package!

I have a few questions however,
- Where is the helm interface noted in the readme? I didn't find any mention of helm in the source code.
- I also couldn't find a function called `travis-goto-project`, but `w` is bound to it.
- Can I list multiple projects? If I use `travis-show-projects` with no arguments, I get some random repositories. Is it possible to list specific repositories of mine?
- I receive this traceback when calling `travis-show-projects` with the project `Kitware/romanesco`:

```
Debugger entered--Lisp error: (wrong-type-argument listp "Python")
  assoc(id (github_language . "Python"))
  create-projects-entries(((repo (github_language . "Python") (last_build_finished_at . "2015-08-24T20:26:44Z") (last_build_started_at . "2015-08-24T20:21:13Z") (last_build_language) (last_build_duration . 331) (last_build_state . "passed") (last_build_number . "602") (last_build_id . 77049202) (description . "A simple analytics execution engine.") (active . t) (slug . "Kitware/romanesco") (id . 2291117))))
```

Emacs Information:

```
This is GNU Emacs 24.4.1 (x86_64-pc-linux-gnu, GTK+ Version 3.14.5)
```

**Comment by nlamirault** [comment]
I remove helm note and refactoring travis-mode.
You could use like that : 

Display all projects : 
```elisp
M-x travis-show-projects 
Projects : danlamanna
```

Display single project : 
```elisp
M-x travis-show-projects 
Projects : danlamanna/pacman-mode
```

**Comment by ice1000** [comment]
> Display all projects :

```
M-x travis-show-projects 
Projects : danlamanna
```

I think you should show this information in the README
